# GENERAL SETTINGS
START = "start"
PLAYING = "playing"
FPS = 60


# TEXT SETTINGS
CURRENT_SCORE = "CURRENT SCORE: "
HIGH_SCORE = "HIGH SCORE: "
PUSH_SPACE_BAR = "PUSH SPACE BAR"
START_THE_GAME = "TO START THE GAME"
EXIT_THE_GAME = "ECS TO EXIT"

# SCREEN SETTINGS
TOP_BOTTOM_BUFFER = 50
WIDTH, HEIGHT = 610, 670
MAZE_WIDTH, MAZE_HEIGHT = \
    WIDTH-TOP_BOTTOM_BUFFER, HEIGHT-TOP_BOTTOM_BUFFER

# FONTS SETTINGS
START_TEXT_SIZE = 16
START_FONT = "arial black"

# COLOR SETTINGS
GREY = (107, 107, 107)
ORANGE = (170, 132, 58)
BLUE = (44, 167, 198)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# PLAYER SETTINGS

# GHOSTS SETTINGS
